### PR TITLE
Fixed #985 : Unittest failed with MinGWx64. And few small improvement…

### LINKED ISSUE #985: Unittest failed with MinGWx64
Hello. I have met some problems. Please consider my report.

Briefly:
```
[----------] Global test environment tear-down
[==========] 355 tests from 29 test cases ran. (879 ms total)
[  PASSED  ] 349 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] OStreamWrapper.ofstream
[  FAILED  ] OStreamWrapper.fstream
[  FAILED  ] PrettyWriter.FileWriteStream
[  FAILED  ] FileStreamTest.FileWriteStream
[  FAILED  ] EncodedStreamTest.EncodedOutputStream
[  FAILED  ] EncodedStreamTest.AutoUTFOutputStream
```

Toolchain version:
```
$ g++ --version
g++.exe (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 6.2.0
$ cmake --version
cmake version 3.7.2
```

RapidJson git version (commit): b596f4e99013dcc2d15f3c71124f15e4330beb3a - lastest in branch *master* at the moment.

Build and run process:
```
$ git clone https://github.com/miloyip/rapidjson
$ cd rapidjson
$ git submodule update --remote --init
$ mkdir build && cd build
$ cmake -G "MinGW Makefiles" ..
$ cmake --build .
$ ctest > ctest.log
$ ./bin/unittest.exe > unittest.log
```

File `ctest.log`:
```
Test project X:/xxx/devel/rapidjson/build
    Start 1: perftest
1/3 Test #1: perftest .........................   Passed   37.04 sec
    Start 2: unittest
2/3 Test #2: unittest .........................***Failed    0.91 sec
    Start 3: valgrind_unittest
Could not find executable valgrind
Looked in the following places:
valgrind
valgrind.exe
Release/valgrind
Release/valgrind.exe
Debug/valgrind
Debug/valgrind.exe
MinSizeRel/valgrind
MinSizeRel/valgrind.exe
RelWithDebInfo/valgrind
RelWithDebInfo/valgrind.exe
Deployment/valgrind
Deployment/valgrind.exe
Development/valgrind
Development/valgrind.exe
3/3 Test #3: valgrind_unittest ................***Not Run   0.00 sec

33% tests passed, 2 tests failed out of 3

Total Test time (real) =  37.96 sec

The following tests FAILED:
	  2 - unittest (Failed)
	  3 - valgrind_unittest (Not Run)
```

File `unittest.log`:
```
RapidJSON v1.1.0
[==========] Running 355 tests from 29 test cases.
[----------] Global test environment set-up.
[----------] 29 tests from Writer
[ RUN      ] Writer.Compact
[       OK ] Writer.Compact (0 ms)
[ RUN      ] Writer.Root
[       OK ] Writer.Root (0 ms)
[ RUN      ] Writer.Int
[       OK ] Writer.Int (0 ms)
[ RUN      ] Writer.UInt
[       OK ] Writer.UInt (0 ms)
[ RUN      ] Writer.Int64
[       OK ] Writer.Int64 (0 ms)
[ RUN      ] Writer.Uint64
[       OK ] Writer.Uint64 (0 ms)
[ RUN      ] Writer.String
[       OK ] Writer.String (0 ms)
[ RUN      ] Writer.Issue_889
[       OK ] Writer.Issue_889 (0 ms)
[ RUN      ] Writer.ScanWriteUnescapedString
[       OK ] Writer.ScanWriteUnescapedString (0 ms)
[ RUN      ] Writer.Double
[       OK ] Writer.Double (0 ms)
[ RUN      ] Writer.Transcode
[       OK ] Writer.Transcode (0 ms)
[ RUN      ] Writer.OStreamWrapper
[       OK ] Writer.OStreamWrapper (0 ms)
[ RUN      ] Writer.AssertRootMayBeAnyValue
[       OK ] Writer.AssertRootMayBeAnyValue (0 ms)
[ RUN      ] Writer.AssertIncorrectObjectLevel
[       OK ] Writer.AssertIncorrectObjectLevel (1 ms)
[ RUN      ] Writer.AssertIncorrectArrayLevel
[       OK ] Writer.AssertIncorrectArrayLevel (0 ms)
[ RUN      ] Writer.AssertIncorrectEndObject
[       OK ] Writer.AssertIncorrectEndObject (0 ms)
[ RUN      ] Writer.AssertIncorrectEndArray
[       OK ] Writer.AssertIncorrectEndArray (0 ms)
[ RUN      ] Writer.AssertObjectKeyNotString
[       OK ] Writer.AssertObjectKeyNotString (0 ms)
[ RUN      ] Writer.AssertMultipleRoot
[       OK ] Writer.AssertMultipleRoot (0 ms)
[ RUN      ] Writer.RootObjectIsComplete
[       OK ] Writer.RootObjectIsComplete (0 ms)
[ RUN      ] Writer.RootArrayIsComplete
[       OK ] Writer.RootArrayIsComplete (0 ms)
[ RUN      ] Writer.RootValueIsComplete
[       OK ] Writer.RootValueIsComplete (0 ms)
[ RUN      ] Writer.InvalidEncoding
[       OK ] Writer.InvalidEncoding (0 ms)
[ RUN      ] Writer.ValidateEncoding
[       OK ] Writer.ValidateEncoding (0 ms)
[ RUN      ] Writer.InvalidEventSequence
[       OK ] Writer.InvalidEventSequence (0 ms)
[ RUN      ] Writer.NaN
[       OK ] Writer.NaN (0 ms)
[ RUN      ] Writer.Inf
[       OK ] Writer.Inf (0 ms)
[ RUN      ] Writer.RawValue
[       OK ] Writer.RawValue (0 ms)
[ RUN      ] Writer.MoveCtor
[       OK ] Writer.MoveCtor (0 ms)
[----------] 29 tests from Writer (1 ms total)

[----------] 34 tests from Value
[ RUN      ] Value.Size
[       OK ] Value.Size (0 ms)
[ RUN      ] Value.DefaultConstructor
[       OK ] Value.DefaultConstructor (0 ms)
[ RUN      ] Value.MoveConstructor
[       OK ] Value.MoveConstructor (0 ms)
[ RUN      ] Value.AssignmentOperator
[       OK ] Value.AssignmentOperator (0 ms)
[ RUN      ] Value.EqualtoOperator
[       OK ] Value.EqualtoOperator (0 ms)
[ RUN      ] Value.CopyFrom
[       OK ] Value.CopyFrom (0 ms)
[ RUN      ] Value.Swap
[       OK ] Value.Swap (0 ms)
[ RUN      ] Value.Null
[       OK ] Value.Null (0 ms)
[ RUN      ] Value.True
[       OK ] Value.True (0 ms)
[ RUN      ] Value.False
[       OK ] Value.False (0 ms)
[ RUN      ] Value.Int
[       OK ] Value.Int (0 ms)
[ RUN      ] Value.Uint
[       OK ] Value.Uint (0 ms)
[ RUN      ] Value.Int64
[       OK ] Value.Int64 (0 ms)
[ RUN      ] Value.Uint64
[       OK ] Value.Uint64 (0 ms)
[ RUN      ] Value.Double
[       OK ] Value.Double (0 ms)
[ RUN      ] Value.Float
[       OK ] Value.Float (0 ms)
[ RUN      ] Value.IsLosslessDouble
[       OK ] Value.IsLosslessDouble (0 ms)
[ RUN      ] Value.IsLosslessFloat
[       OK ] Value.IsLosslessFloat (0 ms)
[ RUN      ] Value.String
[       OK ] Value.String (0 ms)
[ RUN      ] Value.SetStringNullException
[       OK ] Value.SetStringNullException (0 ms)
[ RUN      ] Value.Array
[       OK ] Value.Array (0 ms)
[ RUN      ] Value.ArrayHelper
[       OK ] Value.ArrayHelper (1 ms)
[ RUN      ] Value.ArrayHelperRangeFor
[       OK ] Value.ArrayHelperRangeFor (0 ms)
[ RUN      ] Value.Object
[       OK ] Value.Object (0 ms)
[ RUN      ] Value.ObjectHelper
[       OK ] Value.ObjectHelper (0 ms)
[ RUN      ] Value.ObjectHelperRangeFor
[       OK ] Value.ObjectHelperRangeFor (0 ms)
[ RUN      ] Value.EraseMember_String
[       OK ] Value.EraseMember_String (0 ms)
[ RUN      ] Value.BigNestedArray
[       OK ] Value.BigNestedArray (2 ms)
[ RUN      ] Value.BigNestedObject
[       OK ] Value.BigNestedObject (52 ms)
[ RUN      ] Value.RemoveLastElement
[       OK ] Value.RemoveLastElement (0 ms)
[ RUN      ] Value.AllocateShortString
[       OK ] Value.AllocateShortString (0 ms)
[ RUN      ] Value.AcceptTerminationByHandler
[       OK ] Value.AcceptTerminationByHandler (0 ms)
[ RUN      ] Value.Sorting
[       OK ] Value.Sorting (0 ms)
[ RUN      ] Value.MergeDuplicateKey
[       OK ] Value.MergeDuplicateKey (0 ms)
[----------] 34 tests from Value (56 ms total)

[----------] 11 tests from Document
[ RUN      ] Document.CrtAllocator
[       OK ] Document.CrtAllocator (0 ms)
[ RUN      ] Document.Parse
[       OK ] Document.Parse (0 ms)
[ RUN      ] Document.UnchangedOnParseError
[       OK ] Document.UnchangedOnParseError (0 ms)
[ RUN      ] Document.Parse_Encoding
[       OK ] Document.Parse_Encoding (0 ms)
[ RUN      ] Document.ParseStream_EncodedInputStream
[       OK ] Document.ParseStream_EncodedInputStream (0 ms)
[ RUN      ] Document.ParseStream_AutoUTFInputStream
[       OK ] Document.ParseStream_AutoUTFInputStream (1 ms)
[ RUN      ] Document.Swap
[       OK ] Document.Swap (0 ms)
[ RUN      ] Document.AcceptWriter
[       OK ] Document.AcceptWriter (0 ms)
[ RUN      ] Document.UserBuffer
[       OK ] Document.UserBuffer (0 ms)
[ RUN      ] Document.AssertAcceptInvalidNameType
[       OK ] Document.AssertAcceptInvalidNameType (0 ms)
[ RUN      ] Document.UTF16_Document
[       OK ] Document.UTF16_Document (0 ms)
[----------] 11 tests from Document (1 ms total)

[----------] 1 test from Strtod
[ RUN      ] Strtod.CheckApproximationCase
[       OK ] Strtod.CheckApproximationCase (0 ms)
[----------] 1 test from Strtod (0 ms total)

[----------] 9 tests from StringBuffer
[ RUN      ] StringBuffer.InitialSize
[       OK ] StringBuffer.InitialSize (0 ms)
[ RUN      ] StringBuffer.Put
[       OK ] StringBuffer.Put (0 ms)
[ RUN      ] StringBuffer.PutN_Issue672
[       OK ] StringBuffer.PutN_Issue672 (0 ms)
[ RUN      ] StringBuffer.Clear
[       OK ] StringBuffer.Clear (0 ms)
[ RUN      ] StringBuffer.Push
[       OK ] StringBuffer.Push (0 ms)
[ RUN      ] StringBuffer.Pop
[       OK ] StringBuffer.Pop (0 ms)
[ RUN      ] StringBuffer.GetLength_Issue744
[       OK ] StringBuffer.GetLength_Issue744 (0 ms)
[ RUN      ] StringBuffer.MoveConstructor
[       OK ] StringBuffer.MoveConstructor (0 ms)
[ RUN      ] StringBuffer.MoveAssignment
[       OK ] StringBuffer.MoveAssignment (0 ms)
[----------] 9 tests from StringBuffer (0 ms total)

[----------] 1 test from StrFunc
[ RUN      ] StrFunc.CountStringCodePoint
[       OK ] StrFunc.CountStringCodePoint (0 ms)
[----------] 1 test from StrFunc (0 ms total)

[----------] 4 tests from SIMD
[ RUN      ] SIMD.SkipWhitespace_SSE42
[       OK ] SIMD.SkipWhitespace_SSE42 (0 ms)
[ RUN      ] SIMD.SkipWhitespace_EncodedMemoryStream_SSE42
[       OK ] SIMD.SkipWhitespace_EncodedMemoryStream_SSE42 (0 ms)
[ RUN      ] SIMD.ScanCopyUnescapedString_SSE42
[       OK ] SIMD.ScanCopyUnescapedString_SSE42 (123 ms)
[ RUN      ] SIMD.ScanWriteUnescapedString_SSE42
[       OK ] SIMD.ScanWriteUnescapedString_SSE42 (258 ms)
[----------] 4 tests from SIMD (381 ms total)

[----------] 58 tests from SchemaValidator
[ RUN      ] SchemaValidator.Hasher
[       OK ] SchemaValidator.Hasher (0 ms)
[ RUN      ] SchemaValidator.Typeless
[       OK ] SchemaValidator.Typeless (0 ms)
[ RUN      ] SchemaValidator.MultiType
[       OK ] SchemaValidator.MultiType (0 ms)
[ RUN      ] SchemaValidator.Enum_Typed
[       OK ] SchemaValidator.Enum_Typed (0 ms)
[ RUN      ] SchemaValidator.Enum_Typless
[       OK ] SchemaValidator.Enum_Typless (0 ms)
[ RUN      ] SchemaValidator.Enum_InvalidType
[       OK ] SchemaValidator.Enum_InvalidType (0 ms)
[ RUN      ] SchemaValidator.AllOf
[       OK ] SchemaValidator.AllOf (0 ms)
[ RUN      ] SchemaValidator.AnyOf
[       OK ] SchemaValidator.AnyOf (0 ms)
[ RUN      ] SchemaValidator.OneOf
[       OK ] SchemaValidator.OneOf (0 ms)
[ RUN      ] SchemaValidator.Not
[       OK ] SchemaValidator.Not (0 ms)
[ RUN      ] SchemaValidator.Ref
[       OK ] SchemaValidator.Ref (1 ms)
[ RUN      ] SchemaValidator.Ref_AllOf
[       OK ] SchemaValidator.Ref_AllOf (0 ms)
[ RUN      ] SchemaValidator.String
[       OK ] SchemaValidator.String (0 ms)
[ RUN      ] SchemaValidator.String_LengthRange
[       OK ] SchemaValidator.String_LengthRange (0 ms)
[ RUN      ] SchemaValidator.String_Pattern
[       OK ] SchemaValidator.String_Pattern (0 ms)
[ RUN      ] SchemaValidator.String_Pattern_Invalid
[       OK ] SchemaValidator.String_Pattern_Invalid (0 ms)
[ RUN      ] SchemaValidator.Integer
[       OK ] SchemaValidator.Integer (0 ms)
[ RUN      ] SchemaValidator.Integer_Range
[       OK ] SchemaValidator.Integer_Range (0 ms)
[ RUN      ] SchemaValidator.Integer_Range64Boundary
[       OK ] SchemaValidator.Integer_Range64Boundary (0 ms)
[ RUN      ] SchemaValidator.Integer_RangeU64Boundary
[       OK ] SchemaValidator.Integer_RangeU64Boundary (0 ms)
[ RUN      ] SchemaValidator.Integer_Range64BoundaryExclusive
[       OK ] SchemaValidator.Integer_Range64BoundaryExclusive (0 ms)
[ RUN      ] SchemaValidator.Integer_MultipleOf
[       OK ] SchemaValidator.Integer_MultipleOf (0 ms)
[ RUN      ] SchemaValidator.Integer_MultipleOf64Boundary
[       OK ] SchemaValidator.Integer_MultipleOf64Boundary (0 ms)
[ RUN      ] SchemaValidator.Number_Range
[       OK ] SchemaValidator.Number_Range (0 ms)
[ RUN      ] SchemaValidator.Number_RangeInt
[       OK ] SchemaValidator.Number_RangeInt (0 ms)
[ RUN      ] SchemaValidator.Number_RangeDouble
[       OK ] SchemaValidator.Number_RangeDouble (0 ms)
[ RUN      ] SchemaValidator.Number_RangeDoubleU64Boundary
[       OK ] SchemaValidator.Number_RangeDoubleU64Boundary (0 ms)
[ RUN      ] SchemaValidator.Number_MultipleOf
[       OK ] SchemaValidator.Number_MultipleOf (0 ms)
[ RUN      ] SchemaValidator.Number_MultipleOfOne
[       OK ] SchemaValidator.Number_MultipleOfOne (0 ms)
[ RUN      ] SchemaValidator.Object
[       OK ] SchemaValidator.Object (0 ms)
[ RUN      ] SchemaValidator.Object_Properties
[       OK ] SchemaValidator.Object_Properties (0 ms)
[ RUN      ] SchemaValidator.Object_AdditionalPropertiesBoolean
[       OK ] SchemaValidator.Object_AdditionalPropertiesBoolean (0 ms)
[ RUN      ] SchemaValidator.Object_AdditionalPropertiesObject
[       OK ] SchemaValidator.Object_AdditionalPropertiesObject (0 ms)
[ RUN      ] SchemaValidator.Object_Required
[       OK ] SchemaValidator.Object_Required (0 ms)
[ RUN      ] SchemaValidator.Object_PropertiesRange
[       OK ] SchemaValidator.Object_PropertiesRange (0 ms)
[ RUN      ] SchemaValidator.Object_PropertyDependencies
[       OK ] SchemaValidator.Object_PropertyDependencies (1 ms)
[ RUN      ] SchemaValidator.Object_SchemaDependencies
[       OK ] SchemaValidator.Object_SchemaDependencies (0 ms)
[ RUN      ] SchemaValidator.Object_PatternProperties
[       OK ] SchemaValidator.Object_PatternProperties (0 ms)
[ RUN      ] SchemaValidator.Object_PatternProperties_AdditionalProperties
[       OK ] SchemaValidator.Object_PatternProperties_AdditionalProperties (0 ms)
[ RUN      ] SchemaValidator.Array
[       OK ] SchemaValidator.Array (0 ms)
[ RUN      ] SchemaValidator.Array_ItemsList
[       OK ] SchemaValidator.Array_ItemsList (0 ms)
[ RUN      ] SchemaValidator.Array_ItemsTuple
[       OK ] SchemaValidator.Array_ItemsTuple (0 ms)
[ RUN      ] SchemaValidator.Array_AdditionalItmes
[       OK ] SchemaValidator.Array_AdditionalItmes (0 ms)
[ RUN      ] SchemaValidator.Array_ItemsRange
[       OK ] SchemaValidator.Array_ItemsRange (0 ms)
[ RUN      ] SchemaValidator.Array_UniqueItems
[       OK ] SchemaValidator.Array_UniqueItems (0 ms)
[ RUN      ] SchemaValidator.Boolean
[       OK ] SchemaValidator.Boolean (0 ms)
[ RUN      ] SchemaValidator.Null
[       OK ] SchemaValidator.Null (0 ms)
[ RUN      ] SchemaValidator.ObjectInArray
[       OK ] SchemaValidator.ObjectInArray (0 ms)
[ RUN      ] SchemaValidator.MultiTypeInObject
[       OK ] SchemaValidator.MultiTypeInObject (1 ms)
[ RUN      ] SchemaValidator.MultiTypeWithObject
[       OK ] SchemaValidator.MultiTypeWithObject (0 ms)
[ RUN      ] SchemaValidator.AllOf_Nested
[       OK ] SchemaValidator.AllOf_Nested (0 ms)
[ RUN      ] SchemaValidator.EscapedPointer
[       OK ] SchemaValidator.EscapedPointer (0 ms)
[ RUN      ] SchemaValidator.ValidateMetaSchema
[       OK ] SchemaValidator.ValidateMetaSchema (0 ms)
[ RUN      ] SchemaValidator.ValidateMetaSchema_UTF16
[       OK ] SchemaValidator.ValidateMetaSchema_UTF16 (1 ms)
[ RUN      ] SchemaValidator.TestSuite
Fail: jsonschema/tests/draft4/refRemote.json "change resolution scope" "changed scope ref invalid"
262 / 263 passed (99%)
[       OK ] SchemaValidator.TestSuite (4 ms)
[ RUN      ] SchemaValidator.Issue608
[       OK ] SchemaValidator.Issue608 (0 ms)
[ RUN      ] SchemaValidator.Issue728_AllOfRef
[       OK ] SchemaValidator.Issue728_AllOfRef (0 ms)
[ RUN      ] SchemaValidator.Issue825
[       OK ] SchemaValidator.Issue825 (0 ms)
[----------] 58 tests from SchemaValidator (9 ms total)

[----------] 2 tests from SchemaValidatingReader
[ RUN      ] SchemaValidatingReader.Simple
[       OK ] SchemaValidatingReader.Simple (0 ms)
[ RUN      ] SchemaValidatingReader.Invalid
[       OK ] SchemaValidatingReader.Invalid (0 ms)
[----------] 2 tests from SchemaValidatingReader (0 ms total)

[----------] 1 test from SchemaValidatingWriter
[ RUN      ] SchemaValidatingWriter.Simple
[       OK ] SchemaValidatingWriter.Simple (0 ms)
[----------] 1 test from SchemaValidatingWriter (0 ms total)

[----------] 2 tests from Schema
[ RUN      ] Schema.Issue848
[       OK ] Schema.Issue848 (0 ms)
[ RUN      ] Schema.Issue552
[       OK ] Schema.Issue552 (0 ms)
[----------] 2 tests from Schema (0 ms total)

[----------] 49 tests from Regex
[ RUN      ] Regex.Single
[       OK ] Regex.Single (0 ms)
[ RUN      ] Regex.Concatenation
[       OK ] Regex.Concatenation (0 ms)
[ RUN      ] Regex.Alternation1
[       OK ] Regex.Alternation1 (0 ms)
[ RUN      ] Regex.Alternation2
[       OK ] Regex.Alternation2 (0 ms)
[ RUN      ] Regex.Parenthesis1
[       OK ] Regex.Parenthesis1 (0 ms)
[ RUN      ] Regex.Parenthesis2
[       OK ] Regex.Parenthesis2 (0 ms)
[ RUN      ] Regex.Parenthesis3
[       OK ] Regex.Parenthesis3 (0 ms)
[ RUN      ] Regex.ZeroOrOne1
[       OK ] Regex.ZeroOrOne1 (0 ms)
[ RUN      ] Regex.ZeroOrOne2
[       OK ] Regex.ZeroOrOne2 (0 ms)
[ RUN      ] Regex.ZeroOrOne3
[       OK ] Regex.ZeroOrOne3 (0 ms)
[ RUN      ] Regex.ZeroOrOne4
[       OK ] Regex.ZeroOrOne4 (0 ms)
[ RUN      ] Regex.ZeroOrOne5
[       OK ] Regex.ZeroOrOne5 (0 ms)
[ RUN      ] Regex.ZeroOrMore1
[       OK ] Regex.ZeroOrMore1 (0 ms)
[ RUN      ] Regex.ZeroOrMore2
[       OK ] Regex.ZeroOrMore2 (0 ms)
[ RUN      ] Regex.ZeroOrMore3
[       OK ] Regex.ZeroOrMore3 (0 ms)
[ RUN      ] Regex.ZeroOrMore4
[       OK ] Regex.ZeroOrMore4 (0 ms)
[ RUN      ] Regex.OneOrMore1
[       OK ] Regex.OneOrMore1 (0 ms)
[ RUN      ] Regex.OneOrMore2
[       OK ] Regex.OneOrMore2 (0 ms)
[ RUN      ] Regex.OneOrMore3
[       OK ] Regex.OneOrMore3 (0 ms)
[ RUN      ] Regex.OneOrMore4
[       OK ] Regex.OneOrMore4 (0 ms)
[ RUN      ] Regex.QuantifierExact1
[       OK ] Regex.QuantifierExact1 (0 ms)
[ RUN      ] Regex.QuantifierExact2
[       OK ] Regex.QuantifierExact2 (0 ms)
[ RUN      ] Regex.QuantifierExact3
[       OK ] Regex.QuantifierExact3 (0 ms)
[ RUN      ] Regex.QuantifierMin1
[       OK ] Regex.QuantifierMin1 (0 ms)
[ RUN      ] Regex.QuantifierMin2
[       OK ] Regex.QuantifierMin2 (0 ms)
[ RUN      ] Regex.QuantifierMin3
[       OK ] Regex.QuantifierMin3 (0 ms)
[ RUN      ] Regex.QuantifierMinMax1
[       OK ] Regex.QuantifierMinMax1 (0 ms)
[ RUN      ] Regex.QuantifierMinMax2
[       OK ] Regex.QuantifierMinMax2 (0 ms)
[ RUN      ] Regex.QuantifierMinMax3
[       OK ] Regex.QuantifierMinMax3 (0 ms)
[ RUN      ] Regex.QuantifierMinMax4
[       OK ] Regex.QuantifierMinMax4 (0 ms)
[ RUN      ] Regex.QuantifierMinMax5
[       OK ] Regex.QuantifierMinMax5 (0 ms)
[ RUN      ] Regex.Unicode
[       OK ] Regex.Unicode (0 ms)
[ RUN      ] Regex.AnyCharacter
[       OK ] Regex.AnyCharacter (0 ms)
[ RUN      ] Regex.CharacterRange1
[       OK ] Regex.CharacterRange1 (0 ms)
[ RUN      ] Regex.CharacterRange2
[       OK ] Regex.CharacterRange2 (0 ms)
[ RUN      ] Regex.CharacterRange3
[       OK ] Regex.CharacterRange3 (0 ms)
[ RUN      ] Regex.CharacterRange4
[       OK ] Regex.CharacterRange4 (0 ms)
[ RUN      ] Regex.CharacterRange5
[       OK ] Regex.CharacterRange5 (0 ms)
[ RUN      ] Regex.CharacterRange6
[       OK ] Regex.CharacterRange6 (0 ms)
[ RUN      ] Regex.CharacterRange7
[       OK ] Regex.CharacterRange7 (0 ms)
[ RUN      ] Regex.CharacterRange8
[       OK ] Regex.CharacterRange8 (0 ms)
[ RUN      ] Regex.Search
[       OK ] Regex.Search (0 ms)
[ RUN      ] Regex.Search_BeginAnchor
[       OK ] Regex.Search_BeginAnchor (0 ms)
[ RUN      ] Regex.Search_EndAnchor
[       OK ] Regex.Search_EndAnchor (0 ms)
[ RUN      ] Regex.Search_BothAnchor
[       OK ] Regex.Search_BothAnchor (0 ms)
[ RUN      ] Regex.Escape
[       OK ] Regex.Escape (0 ms)
[ RUN      ] Regex.Invalid
[       OK ] Regex.Invalid (0 ms)
[ RUN      ] Regex.Issue538
[       OK ] Regex.Issue538 (0 ms)
[ RUN      ] Regex.Issue583
[       OK ] Regex.Issue583 (5 ms)
[----------] 49 tests from Regex (6 ms total)

[----------] 54 tests from Reader
[ RUN      ] Reader.ParseTrue
[       OK ] Reader.ParseTrue (0 ms)
[ RUN      ] Reader.ParseFalse
[       OK ] Reader.ParseFalse (0 ms)
[ RUN      ] Reader.ParseNumber_Integer
[       OK ] Reader.ParseNumber_Integer (26 ms)
[ RUN      ] Reader.ParseNumber_NormalPrecisionDouble
[       OK ] Reader.ParseNumber_NormalPrecisionDouble (43 ms)
[ RUN      ] Reader.ParseNumber_FullPrecisionDouble
[       OK ] Reader.ParseNumber_FullPrecisionDouble (66 ms)
[ RUN      ] Reader.ParseNumber_NormalPrecisionError
ULP Average = 0.341283, Max = 2 
[       OK ] Reader.ParseNumber_NormalPrecisionError (223 ms)
[ RUN      ] Reader.ParseNumber_Error
[       OK ] Reader.ParseNumber_Error (0 ms)
[ RUN      ] Reader.ParseString
[       OK ] Reader.ParseString (0 ms)
[ RUN      ] Reader.ParseString_Transcoding
[       OK ] Reader.ParseString_Transcoding (0 ms)
[ RUN      ] Reader.ParseString_TranscodingWithValidation
[       OK ] Reader.ParseString_TranscodingWithValidation (0 ms)
[ RUN      ] Reader.ParseString_NonDestructive
[       OK ] Reader.ParseString_NonDestructive (0 ms)
[ RUN      ] Reader.ParseString_Error
[       OK ] Reader.ParseString_Error (0 ms)
[ RUN      ] Reader.ParseEmptyArray
[       OK ] Reader.ParseEmptyArray (0 ms)
[ RUN      ] Reader.ParseArray
[       OK ] Reader.ParseArray (0 ms)
[ RUN      ] Reader.ParseArray_Error
[       OK ] Reader.ParseArray_Error (0 ms)
[ RUN      ] Reader.ParseObject
[       OK ] Reader.ParseObject (0 ms)
[ RUN      ] Reader.Parse_EmptyObject
[       OK ] Reader.Parse_EmptyObject (0 ms)
[ RUN      ] Reader.Parse_MultipleRoot
[       OK ] Reader.Parse_MultipleRoot (0 ms)
[ RUN      ] Reader.ParseIterative_MultipleRoot
[       OK ] Reader.ParseIterative_MultipleRoot (0 ms)
[ RUN      ] Reader.ParseInsitu_MultipleRoot
[       OK ] Reader.ParseInsitu_MultipleRoot (0 ms)
[ RUN      ] Reader.ParseInsituIterative_MultipleRoot
[       OK ] Reader.ParseInsituIterative_MultipleRoot (0 ms)
[ RUN      ] Reader.ParseDocument_Error
[       OK ] Reader.ParseDocument_Error (0 ms)
[ RUN      ] Reader.ParseValue_Error
[       OK ] Reader.ParseValue_Error (0 ms)
[ RUN      ] Reader.ParseObject_Error
[       OK ] Reader.ParseObject_Error (0 ms)
[ RUN      ] Reader.SkipWhitespace
[       OK ] Reader.SkipWhitespace (0 ms)
[ RUN      ] Reader.CustomStringStream
[       OK ] Reader.CustomStringStream (0 ms)
[ RUN      ] Reader.Parse_IStreamWrapper_StringStream
[       OK ] Reader.Parse_IStreamWrapper_StringStream (0 ms)
[ RUN      ] Reader.IterativeParsing_ErrorHandling
[       OK ] Reader.IterativeParsing_ErrorHandling (0 ms)
[ RUN      ] Reader.IterativeParsing_General
[       OK ] Reader.IterativeParsing_General (0 ms)
[ RUN      ] Reader.IterativeParsing_Count
[       OK ] Reader.IterativeParsing_Count (0 ms)
[ RUN      ] Reader.IterativePullParsing_General
[       OK ] Reader.IterativePullParsing_General (0 ms)
[ RUN      ] Reader.IterativeParsing_ShortCircuit
[       OK ] Reader.IterativeParsing_ShortCircuit (0 ms)
[ RUN      ] Reader.BaseReaderHandler_Default
[       OK ] Reader.BaseReaderHandler_Default (0 ms)
[ RUN      ] Reader.ParseTerminationByHandler
[       OK ] Reader.ParseTerminationByHandler (0 ms)
[ RUN      ] Reader.ParseComments
[       OK ] Reader.ParseComments (0 ms)
[ RUN      ] Reader.ParseEmptyInlineComment
[       OK ] Reader.ParseEmptyInlineComment (0 ms)
[ RUN      ] Reader.ParseEmptyOnelineComment
[       OK ] Reader.ParseEmptyOnelineComment (0 ms)
[ RUN      ] Reader.ParseMultipleCommentsInARow
[       OK ] Reader.ParseMultipleCommentsInARow (0 ms)
[ RUN      ] Reader.InlineCommentsAreDisabledByDefault
[       OK ] Reader.InlineCommentsAreDisabledByDefault (0 ms)
[ RUN      ] Reader.OnelineCommentsAreDisabledByDefault
[       OK ] Reader.OnelineCommentsAreDisabledByDefault (0 ms)
[ RUN      ] Reader.EofAfterOneLineComment
[       OK ] Reader.EofAfterOneLineComment (0 ms)
[ RUN      ] Reader.IncompleteMultilineComment
[       OK ] Reader.IncompleteMultilineComment (0 ms)
[ RUN      ] Reader.IncompleteMultilineComment2
[       OK ] Reader.IncompleteMultilineComment2 (0 ms)
[ RUN      ] Reader.UnrecognizedComment
[       OK ] Reader.UnrecognizedComment (0 ms)
[ RUN      ] Reader.NumbersAsStrings
[       OK ] Reader.NumbersAsStrings (0 ms)
[ RUN      ] Reader.TrailingCommas
[       OK ] Reader.TrailingCommas (0 ms)
[ RUN      ] Reader.TrailingCommasIterative
[       OK ] Reader.TrailingCommasIterative (0 ms)
[ RUN      ] Reader.MultipleTrailingCommaErrors
[       OK ] Reader.MultipleTrailingCommaErrors (0 ms)
[ RUN      ] Reader.MultipleTrailingCommaErrorsIterative
[       OK ] Reader.MultipleTrailingCommaErrorsIterative (0 ms)
[ RUN      ] Reader.EmptyExceptForCommaErrors
[       OK ] Reader.EmptyExceptForCommaErrors (0 ms)
[ RUN      ] Reader.EmptyExceptForCommaErrorsIterative
[       OK ] Reader.EmptyExceptForCommaErrorsIterative (0 ms)
[ RUN      ] Reader.TrailingCommaHandlerTermination
[       OK ] Reader.TrailingCommaHandlerTermination (1 ms)
[ RUN      ] Reader.TrailingCommaHandlerTerminationIterative
[       OK ] Reader.TrailingCommaHandlerTerminationIterative (0 ms)
[ RUN      ] Reader.ParseNanAndInfinity
[       OK ] Reader.ParseNanAndInfinity (0 ms)
[----------] 54 tests from Reader (359 ms total)

[----------] 7 tests from OStreamWrapper
[ RUN      ] OStreamWrapper.ostringstream
[       OK ] OStreamWrapper.ostringstream (0 ms)
[ RUN      ] OStreamWrapper.stringstream
[       OK ] OStreamWrapper.stringstream (0 ms)
[ RUN      ] OStreamWrapper.wostringstream
[       OK ] OStreamWrapper.wostringstream (0 ms)
[ RUN      ] OStreamWrapper.wstringstream
[       OK ] OStreamWrapper.wstringstream (0 ms)
[ RUN      ] OStreamWrapper.cout
Hello World!
[       OK ] OStreamWrapper.cout (0 ms)
[ RUN      ] OStreamWrapper.ofstream
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'H' (72, 0x48)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'e' (101, 0x65)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'l' (108, 0x6C)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'l' (108, 0x6C)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'o' (111, 0x6F)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: ' ' (32, 0x20)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'W' (87, 0x57)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'o' (111, 0x6F)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'r' (114, 0x72)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'l' (108, 0x6C)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'd' (100, 0x64)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: '!' (33, 0x21)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: '\n' (10, 0xA)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
With diff:
@@ -1,2 +1,1 @@
-'
-' (10, 0xA)
+'\xFF' (255)

[  FAILED  ] OStreamWrapper.ofstream (1 ms)
[ RUN      ] OStreamWrapper.fstream
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'H' (72, 0x48)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'e' (101, 0x65)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'l' (108, 0x6C)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'l' (108, 0x6C)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'o' (111, 0x6F)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: ' ' (32, 0x20)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'W' (87, 0x57)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'o' (111, 0x6F)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'r' (114, 0x72)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'l' (108, 0x6C)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: 'd' (100, 0x64)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: '!' (33, 0x21)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
X:\xxx\devel\rapidjson\test\unittest\ostreamwrappertest.cpp:81: Failure
      Expected: *p
      Which is: '\n' (10, 0xA)
To be equal to: static_cast<char>(fgetc(fp))
      Which is: '\xFF' (255)
With diff:
@@ -1,2 +1,1 @@
-'
-' (10, 0xA)
+'\xFF' (255)

[  FAILED  ] OStreamWrapper.fstream (0 ms)
[----------] 7 tests from OStreamWrapper (1 ms total)

[----------] 13 tests from PrettyWriter
[ RUN      ] PrettyWriter.Basic
[       OK ] PrettyWriter.Basic (0 ms)
[ RUN      ] PrettyWriter.FormatOptions
[       OK ] PrettyWriter.FormatOptions (0 ms)
[ RUN      ] PrettyWriter.SetIndent
[       OK ] PrettyWriter.SetIndent (0 ms)
[ RUN      ] PrettyWriter.String
[       OK ] PrettyWriter.String (0 ms)
[ RUN      ] PrettyWriter.String_STDSTRING
[       OK ] PrettyWriter.String_STDSTRING (0 ms)
[ RUN      ] PrettyWriter.OStreamWrapper
[       OK ] PrettyWriter.OStreamWrapper (0 ms)
[ RUN      ] PrettyWriter.FileWriteStream
unknown file: Failure
C++ exception with description "fp_ != 0" thrown in the test body.
[  FAILED  ] PrettyWriter.FileWriteStream (0 ms)
[ RUN      ] PrettyWriter.RawValue
[       OK ] PrettyWriter.RawValue (0 ms)
[ RUN      ] PrettyWriter.InvalidEventSequence
[       OK ] PrettyWriter.InvalidEventSequence (0 ms)
[ RUN      ] PrettyWriter.NaN
[       OK ] PrettyWriter.NaN (0 ms)
[ RUN      ] PrettyWriter.Inf
[       OK ] PrettyWriter.Inf (0 ms)
[ RUN      ] PrettyWriter.Issue_889
[       OK ] PrettyWriter.Issue_889 (0 ms)
[ RUN      ] PrettyWriter.MoveCtor
[       OK ] PrettyWriter.MoveCtor (0 ms)
[----------] 13 tests from PrettyWriter (0 ms total)

[----------] 36 tests from Pointer
[ RUN      ] Pointer.DefaultConstructor
[       OK ] Pointer.DefaultConstructor (0 ms)
[ RUN      ] Pointer.Parse
[       OK ] Pointer.Parse (0 ms)
[ RUN      ] Pointer.Parse_URIFragment
[       OK ] Pointer.Parse_URIFragment (0 ms)
[ RUN      ] Pointer.Stringify
[       OK ] Pointer.Stringify (0 ms)
[ RUN      ] Pointer.ConstructorWithToken
[       OK ] Pointer.ConstructorWithToken (0 ms)
[ RUN      ] Pointer.CopyConstructor
[       OK ] Pointer.CopyConstructor (0 ms)
[ RUN      ] Pointer.Assignment
[       OK ] Pointer.Assignment (0 ms)
[ RUN      ] Pointer.Append
[       OK ] Pointer.Append (0 ms)
[ RUN      ] Pointer.Equality
[       OK ] Pointer.Equality (0 ms)
[ RUN      ] Pointer.Inequality
[       OK ] Pointer.Inequality (0 ms)
[ RUN      ] Pointer.Create
[       OK ] Pointer.Create (0 ms)
[ RUN      ] Pointer.Get
[       OK ] Pointer.Get (0 ms)
[ RUN      ] Pointer.GetWithDefault
[       OK ] Pointer.GetWithDefault (0 ms)
[ RUN      ] Pointer.GetWithDefault_NoAllocator
[       OK ] Pointer.GetWithDefault_NoAllocator (0 ms)
[ RUN      ] Pointer.Set
[       OK ] Pointer.Set (0 ms)
[ RUN      ] Pointer.Set_NoAllocator
[       OK ] Pointer.Set_NoAllocator (0 ms)
[ RUN      ] Pointer.Swap
[       OK ] Pointer.Swap (0 ms)
[ RUN      ] Pointer.Swap_NoAllocator
[       OK ] Pointer.Swap_NoAllocator (0 ms)
[ RUN      ] Pointer.Erase
[       OK ] Pointer.Erase (0 ms)
[ RUN      ] Pointer.CreateValueByPointer
[       OK ] Pointer.CreateValueByPointer (0 ms)
[ RUN      ] Pointer.CreateValueByPointer_NoAllocator
[       OK ] Pointer.CreateValueByPointer_NoAllocator (0 ms)
[ RUN      ] Pointer.GetValueByPointer
[       OK ] Pointer.GetValueByPointer (0 ms)
[ RUN      ] Pointer.GetValueByPointerWithDefault_Pointer
[       OK ] Pointer.GetValueByPointerWithDefault_Pointer (0 ms)
[ RUN      ] Pointer.GetValueByPointerWithDefault_String
[       OK ] Pointer.GetValueByPointerWithDefault_String (0 ms)
[ RUN      ] Pointer.GetValueByPointerWithDefault_Pointer_NoAllocator
[       OK ] Pointer.GetValueByPointerWithDefault_Pointer_NoAllocator (0 ms)
[ RUN      ] Pointer.GetValueByPointerWithDefault_String_NoAllocator
[       OK ] Pointer.GetValueByPointerWithDefault_String_NoAllocator (0 ms)
[ RUN      ] Pointer.SetValueByPointer_Pointer
[       OK ] Pointer.SetValueByPointer_Pointer (0 ms)
[ RUN      ] Pointer.SetValueByPointer_String
[       OK ] Pointer.SetValueByPointer_String (0 ms)
[ RUN      ] Pointer.SetValueByPointer_Pointer_NoAllocator
[       OK ] Pointer.SetValueByPointer_Pointer_NoAllocator (1 ms)
[ RUN      ] Pointer.SetValueByPointer_String_NoAllocator
[       OK ] Pointer.SetValueByPointer_String_NoAllocator (0 ms)
[ RUN      ] Pointer.SwapValueByPointer
[       OK ] Pointer.SwapValueByPointer (0 ms)
[ RUN      ] Pointer.SwapValueByPointer_NoAllocator
[       OK ] Pointer.SwapValueByPointer_NoAllocator (0 ms)
[ RUN      ] Pointer.EraseValueByPointer_Pointer
[       OK ] Pointer.EraseValueByPointer_Pointer (0 ms)
[ RUN      ] Pointer.EraseValueByPointer_String
[       OK ] Pointer.EraseValueByPointer_String (0 ms)
[ RUN      ] Pointer.Ambiguity
[       OK ] Pointer.Ambiguity (0 ms)
[ RUN      ] Pointer.Issue483
[       OK ] Pointer.Issue483 (0 ms)
[----------] 36 tests from Pointer (2 ms total)

[----------] 2 tests from NamespaceTest
[ RUN      ] NamespaceTest.Using
[       OK ] NamespaceTest.Using (0 ms)
[ RUN      ] NamespaceTest.Direct
[       OK ] NamespaceTest.Direct (0 ms)
[----------] 2 tests from NamespaceTest (0 ms total)

[----------] 1 test from JsonChecker
[ RUN      ] JsonChecker.Reader
[       OK ] JsonChecker.Reader (5 ms)
[----------] 1 test from JsonChecker (5 ms total)

[----------] 6 tests from IStreamWrapper
[ RUN      ] IStreamWrapper.istringstream
[       OK ] IStreamWrapper.istringstream (0 ms)
[ RUN      ] IStreamWrapper.stringstream
[       OK ] IStreamWrapper.stringstream (0 ms)
[ RUN      ] IStreamWrapper.wistringstream
[       OK ] IStreamWrapper.wistringstream (0 ms)
[ RUN      ] IStreamWrapper.wstringstream
[       OK ] IStreamWrapper.wstringstream (0 ms)
[ RUN      ] IStreamWrapper.ifstream
[       OK ] IStreamWrapper.ifstream (0 ms)
[ RUN      ] IStreamWrapper.fstream
[       OK ] IStreamWrapper.fstream (0 ms)
[----------] 6 tests from IStreamWrapper (0 ms total)

[----------] 4 tests from itoa
[ RUN      ] itoa.u32toa
[       OK ] itoa.u32toa (0 ms)
[ RUN      ] itoa.i32toa
[       OK ] itoa.i32toa (0 ms)
[ RUN      ] itoa.u64toa
[       OK ] itoa.u64toa (0 ms)
[ RUN      ] itoa.i64toa
[       OK ] itoa.i64toa (0 ms)
[----------] 4 tests from itoa (0 ms total)

[----------] 2 tests from FileStreamTest
[ RUN      ] FileStreamTest.FileReadStream
[       OK ] FileStreamTest.FileReadStream (16 ms)
[ RUN      ] FileStreamTest.FileWriteStream
unknown file: Failure
C++ exception with description "fp_ != 0" thrown in the test body.
[  FAILED  ] FileStreamTest.FileWriteStream (0 ms)
[----------] 2 tests from FileStreamTest (17 ms total)

[----------] 1 test from Fwd
[ RUN      ] Fwd.Fwd
[       OK ] Fwd.Fwd (0 ms)
[----------] 1 test from Fwd (0 ms total)

[----------] 4 tests from EncodingsTest
[ RUN      ] EncodingsTest.UTF8
[       OK ] EncodingsTest.UTF8 (19 ms)
[ RUN      ] EncodingsTest.UTF16
[       OK ] EncodingsTest.UTF16 (13 ms)
[ RUN      ] EncodingsTest.UTF32
[       OK ] EncodingsTest.UTF32 (5 ms)
[ RUN      ] EncodingsTest.ASCII
[       OK ] EncodingsTest.ASCII (0 ms)
[----------] 4 tests from EncodingsTest (37 ms total)

[----------] 4 tests from EncodedStreamTest
[ RUN      ] EncodedStreamTest.EncodedInputStream
[       OK ] EncodedStreamTest.EncodedInputStream (1 ms)
[ RUN      ] EncodedStreamTest.AutoUTFInputStream
[       OK ] EncodedStreamTest.AutoUTFInputStream (2 ms)
[ RUN      ] EncodedStreamTest.EncodedOutputStream
unknown file: Failure
C++ exception with description "fp_ != 0" thrown in the test body.
[  FAILED  ] EncodedStreamTest.EncodedOutputStream (0 ms)
[ RUN      ] EncodedStreamTest.AutoUTFOutputStream
unknown file: Failure
C++ exception with description "fp_ != 0" thrown in the test body.
[  FAILED  ] EncodedStreamTest.AutoUTFOutputStream (0 ms)
[----------] 4 tests from EncodedStreamTest (3 ms total)

[----------] 2 tests from dtoa
[ RUN      ] dtoa.normal
[       OK ] dtoa.normal (0 ms)
[ RUN      ] dtoa.maxDecimalPlaces
[       OK ] dtoa.maxDecimalPlaces (0 ms)
[----------] 2 tests from dtoa (0 ms total)

[----------] 4 tests from DocumentMove/0, where TypeParam = rapidjson::CrtAllocator
[ RUN      ] DocumentMove/0.MoveConstructor
[       OK ] DocumentMove/0.MoveConstructor (0 ms)
[ RUN      ] DocumentMove/0.MoveConstructorParseError
[       OK ] DocumentMove/0.MoveConstructorParseError (0 ms)
[ RUN      ] DocumentMove/0.MoveAssignment
[       OK ] DocumentMove/0.MoveAssignment (0 ms)
[ RUN      ] DocumentMove/0.MoveAssignmentParseError
[       OK ] DocumentMove/0.MoveAssignmentParseError (0 ms)
[----------] 4 tests from DocumentMove/0 (0 ms total)

[----------] 4 tests from DocumentMove/1, where TypeParam = rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>
[ RUN      ] DocumentMove/1.MoveConstructor
[       OK ] DocumentMove/1.MoveConstructor (0 ms)
[ RUN      ] DocumentMove/1.MoveConstructorParseError
[       OK ] DocumentMove/1.MoveConstructorParseError (0 ms)
[ RUN      ] DocumentMove/1.MoveAssignment
[       OK ] DocumentMove/1.MoveAssignment (0 ms)
[ RUN      ] DocumentMove/1.MoveAssignmentParseError
[       OK ] DocumentMove/1.MoveAssignmentParseError (0 ms)
[----------] 4 tests from DocumentMove/1 (0 ms total)

[----------] 6 tests from BigInteger
[ RUN      ] BigInteger.Constructor
[       OK ] BigInteger.Constructor (1 ms)
[ RUN      ] BigInteger.AddUint64
[       OK ] BigInteger.AddUint64 (0 ms)
[ RUN      ] BigInteger.MultiplyUint64
[       OK ] BigInteger.MultiplyUint64 (0 ms)
[ RUN      ] BigInteger.MultiplyUint32
[       OK ] BigInteger.MultiplyUint32 (0 ms)
[ RUN      ] BigInteger.LeftShift
[       OK ] BigInteger.LeftShift (0 ms)
[ RUN      ] BigInteger.Compare
[       OK ] BigInteger.Compare (0 ms)
[----------] 6 tests from BigInteger (1 ms total)

[----------] 4 tests from Allocator
[ RUN      ] Allocator.CrtAllocator
[       OK ] Allocator.CrtAllocator (0 ms)
[ RUN      ] Allocator.MemoryPoolAllocator
[       OK ] Allocator.MemoryPoolAllocator (0 ms)
[ RUN      ] Allocator.Alignment
[       OK ] Allocator.Alignment (0 ms)
[ RUN      ] Allocator.Issue399
[       OK ] Allocator.Issue399 (0 ms)
[----------] 4 tests from Allocator (0 ms total)

[----------] Global test environment tear-down
[==========] 355 tests from 29 test cases ran. (879 ms total)
[  PASSED  ] 349 tests.
[  FAILED  ] 6 tests, listed below:
[  FAILED  ] OStreamWrapper.ofstream
[  FAILED  ] OStreamWrapper.fstream
[  FAILED  ] PrettyWriter.FileWriteStream
[  FAILED  ] FileStreamTest.FileWriteStream
[  FAILED  ] EncodedStreamTest.EncodedOutputStream
[  FAILED  ] EncodedStreamTest.AutoUTFOutputStream

 6 FAILED TESTS
```

### PR DESCRIPTION
**Pull request by sledgeh**
… were done while looking for mistakes.

Problem was because of Windows uses backslashes '\\', not Unix '/'

### CODE REVIEW

File: test/unittest/unittest.h [hunk 1]
```diff
@@ -78,7 +78,7 @@ inline Ch* StrDup(const Ch* str) {
 }
 
 inline FILE* TempFile(char *filename) {
-#ifdef _MSC_VER
+#if defined(__WIN32__) || defined(_MSC_VER)
```
Comment (sledgeh) [inline test/unittest/unittest.h]: Only this change really need to fix #985

**Comment by miloyip** [comment]
Thank you

**Comment by sledgeh** [comment]
I am glad to participate.
